TC#032 Login page: Verification login to user account with invalid e-mail
N1ki4/Dp-195-TAQC pull request #10
Opened 2020-12-05 22:21 UTC by ElVolya

TC#032-Login-page-verification-login-to-user-account-with-invalid-e-mail

2020-12-06 11:34 UTC, moiseienko-dg requested changes

2020-12-06 11:34 UTC, moiseienko-dg commented on 032.md
> +### Test Case Summary: Login page: Verification login to user account with invalid e-mail
login должен прописываться как log in, т.к. это глагол

2020-12-06 19:19 UTC, ElVolya commented on 032.md
> +### Test Case Summary: Login page: Verification login to user account with invalid e-mail
Дим, исправила

2020-12-06 19:57 UTC, moiseienko-dg approved these changes

2020-12-07 07:32 UTC, SerhiiKhyzhko approved these changes

2020-12-08 07:10 UTC, YuriiShp approved these changes

2020-12-08 12:15 UTC, N1ki4 approved these changes

2020-12-08 12:16 UTC, merged