TC#046 Registration page verification of new user registration with invalid data and valid email
N1ki4/Dp-195-TAQC pull request #12
Opened 2020-12-05 23:45 UTC by ElVolya

2020-12-06 11:47 UTC, moiseienko-dg requested changes

2020-12-06 11:47 UTC, moiseienko-dg commented on 046.md
> +2. Open 'Registration page'
page не нужно брать в кавычкп

2020-12-06 19:24 UTC, ElVolya commented on 046.md
> +2. Open 'Registration page'
Исправила

2020-12-06 19:57 UTC, moiseienko-dg approved these changes

2020-12-07 07:36 UTC, SerhiiKhyzhko approved these changes

2020-12-08 07:06 UTC, YuriiShp approved these changes

2020-12-08 15:40 UTC, N1ki4 approved these changes

2020-12-08 15:41 UTC, merged