TC_007 added
N1ki4/Dp-195-TAQC pull request #2
Opened 2020-12-04 15:30 UTC by YuriiShp

add TC_007 to the develop branch

2020-12-04 22:13 UTC, zoiaivanova approved these changes

2020-12-05 09:18 UTC, ElVolya approved these changes

2020-12-05 09:52 UTC, moiseienko-dg commented on TC_007.md
> +|       4       | Click "Submit" button     |  | Redirect to "./success" URL
Redirect скорее сам процесс, чем то, что мы видими итого
предлагаю этот этап назвать "Contact Us Success Page"

2020-12-05 09:52 UTC, moiseienko-dg commented on TC_007.md
> +Contact page: "Contact US" form submission with valid data
мы договорились, что Page как объект будет с большой буквы
ex. Contact Page

2020-12-05 09:56 UTC, moiseienko-dg requested changes

2020-12-05 09:56 UTC, moiseienko-dg commented on TC_007.md
> +|       4       | Click "Submit" button     |  | Redirect to "./success" URL
Redirect скорее сам процесс, чем то, что мы видими итого
предлагаю этот этап назвать "Contact Us Success Page"

2020-12-05 09:56 UTC, moiseienko-dg commented on TC_007.md
> +Contact page: "Contact US" form submission with valid data
мы договорились, что Page как объект будет с большой буквы
ex. Contact Page

2020-12-05 11:34 UTC, moiseienko-dg requested changes

2020-12-05 11:34 UTC, moiseienko-dg commented on TC_007.md
> +Contact page: "Contact US" form submission with valid data
мы договорились, что Page как объект будет с большой буквы
ex. Contact Page

2020-12-05 11:34 UTC, moiseienko-dg commented on TC_007.md
> +|       4       | Click "Submit" button     |  | Redirect to "./success" URL
Redirect скорее сам процесс, чем то, что мы видими итого
предлагаю этот этап назвать "Contact Us Success Page"

2020-12-06 21:13 UTC, YuriiShp commented on TC_007.md
> +|       4       | Click "Submit" button     |  | Redirect to "./success" URL
Виправлено

2020-12-06 21:14 UTC, YuriiShp commented on TC_007.md
> +Contact page: "Contact US" form submission with valid data
Виправлено

2020-12-06 21:23 UTC, moiseienko-dg approved these changes

2020-12-07 07:19 UTC, SerhiiKhyzhko approved these changes

2020-12-08 11:56 UTC, N1ki4 approved these changes

2020-12-08 12:13 UTC, merged