TC#001 Registration Page: Verification of new User Registration with valid data
N1ki4/Dp-195-TAQC pull request #7
Opened 2020-12-05 20:58 UTC by ElVolya

2020-12-06 11:23 UTC, moiseienko-dg requested changes

2020-12-06 11:23 UTC, moiseienko-dg commented on 001.md
> +|       6       | Fill 'Password Confirm'	|	Valid password	"Password Confirm" | input is filled with given text data	|
вместо input думаю стоит писать field, как обсуждали на занятии

2020-12-06 19:34 UTC, ElVolya commented on 001.md
> +Test case check a Creating a new account
согласна, поменяла

2020-12-06 19:35 UTC, ElVolya commented on 001.md
> +|       6       | Fill 'Password Confirm'	|	Valid password	"Password Confirm" | input is filled with given text data	|
агась. внесла изменения

2020-12-06 19:51 UTC, YuriiShp approved these changes

2020-12-06 19:52 UTC, moiseienko-dg approved these changes

2020-12-07 07:26 UTC, SerhiiKhyzhko approved these changes

2020-12-08 11:52 UTC, closed without merging