TC#002 Login page: Verification an existing user login with valid credentials
N1ki4/Dp-195-TAQC pull request #8
Opened 2020-12-05 21:29 UTC by ElVolya

Login page: Verification an existing user login with valid credentials

2020-12-06 11:28 UTC, moiseienko-dg requested changes

2020-12-06 11:28 UTC, moiseienko-dg commented on 002.md
> +Login to the user account with valid data
Login следует писать как Log in, т.к. в данном случае это глагол, а не существительное (если я правильно понял)

2020-12-06 11:28 UTC, moiseienko-dg commented on 002.md
> +|       3       | Click 'Login' button |  | Displayed 'Account' page' |
за page лишняя кавычка

2020-12-06 11:28 UTC, moiseienko-dg commented on 002.md
> +|       2       | Fill 'Password' field | Valid  password of existing user | 'Password' input is filled with given text data |
думаю вместо input нужно использовать field

2020-12-06 18:39 UTC, ElVolya commented on 002.md
> +Login to the user account with valid data
Исправила

2020-12-06 18:40 UTC, ElVolya commented on 002.md
> +|       2       | Fill 'Password' field | Valid  password of existing user | 'Password' input is filled with given text data |
Поменяла

2020-12-06 18:50 UTC, N1ki4 approved these changes

2020-12-06 18:57 UTC, ElVolya reviewed
Файл отредактирован, согласно всем замечаниям

2020-12-06 18:57 UTC, ElVolya commented on 002.md
> +|       3       | Click 'Login' button |  | Displayed 'Account' page' |
готово

2020-12-06 19:53 UTC, moiseienko-dg approved these changes

2020-12-07 00:59 UTC, zoiaivanova approved these changes

2020-12-07 07:29 UTC, SerhiiKhyzhko approved these changes

2020-12-08 12:15 UTC, merged