TC#030 Login page: Verification login to user account with invalid password
N1ki4/Dp-195-TAQC pull request #9
Opened 2020-12-05 21:57 UTC by ElVolya

Login page: Verification login to user account with invalid password

2020-12-06 11:32 UTC, moiseienko-dg requested changes

2020-12-06 11:32 UTC, moiseienko-dg commented on 030.md
> +|       3       | Click 'Login' button |  | Despaed notification ' Warning: No match for E-Mail Address and/or Password.' |
думаю этот функционал можно оформить через параметры  (@e-mail, @password)
и сделать пару итераций: допустим на первой ввест верный e-mail, но не правильный пароль, а на второй итерации наоборот

2020-12-06 19:07 UTC, ElVolya commented on 030.md
> +|       3       | Click 'Login' button |  | Despaed notification ' Warning: No match for E-Mail Address and/or Password.' |
1. Спасибо за замечание. Поменяла на параметры (@E-mail, @password)
2. Для этого создан отдельный тест кейс, т.к. один тест кейс описывает один сценарий

2020-12-06 19:56 UTC, moiseienko-dg commented on 030.md
> +|       3       | Click 'Login' button |  | Despaed notification ' Warning: No match for E-Mail Address and/or Password.' |
понял

2020-12-06 19:56 UTC, moiseienko-dg approved these changes

2020-12-07 07:31 UTC, SerhiiKhyzhko approved these changes

2020-12-08 07:15 UTC, YuriiShp approved these changes

2020-12-08 12:15 UTC, N1ki4 approved these changes

2020-12-08 12:15 UTC, merged